controllerManager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --enable-hr-autodiscovery=false
    - --log-format=json
    - --log-level=info
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
    image:
      repository: ghcr.io/nebius/helmrelease-trigger-operator
      tag: 0.2.0
    resources: 
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  replicas: 1
  serviceAccount: 
    annotations: {}
fullnameOverride: helmrelease-trigger
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
kubernetesClusterDomain: cluster.local
